"use client";
import { useMemo, useState } from "react";
import { categories, menuItems } from "@/data/menu";
import { CakeSize, Food } from "@/types/menu";
type OrderLine = { food: Food; size?: CakeSize; quantity: number };
const birr = (price: number) => `ETB ${price.toLocaleString()}`;

export default function MenuExperience() {
  const [language, setLanguage] = useState<"en" | "am">("en"); const [category, setCategory] = useState("All"); const [query, setQuery] = useState(""); const [selected, setSelected] = useState<Food | null>(null); const [orderOpen, setOrderOpen] = useState(false); const [order, setOrder] = useState<OrderLine[]>([]); const [items] = useState(() => { if (typeof window === "undefined") return menuItems; const saved = window.localStorage.getItem("hasset-menu-items"); return saved ? JSON.parse(saved) as Food[] : menuItems; });
  const products = useMemo(() => items.filter(item => item.isVisible && (category === "All" || item.category === category) && `${item.name} ${item.nameAm} ${item.description}`.toLowerCase().includes(query.toLowerCase())), [items, category, query]);
  const count = order.reduce((sum, line) => sum + line.quantity, 0); const total = order.reduce((sum, line) => sum + (line.size?.price ?? line.food.price) * line.quantity, 0);
  const add = (food: Food, size = food.sizes?.find(value => value.name === "1 KG") ?? food.sizes?.[0]) => { if (food.isSoldOut) return; setOrder(previous => { const hit = previous.find(line => line.food.id === food.id && line.size?.name === size?.name); return hit ? previous.map(line => line === hit ? { ...line, quantity: line.quantity + 1 } : line) : [...previous, { food, size, quantity: 1 }]; }); setSelected(null); };
  const adjust = (index: number, amount: number) => setOrder(previous => previous.flatMap((line, i) => i !== index ? [line] : line.quantity + amount < 1 ? [] : [{ ...line, quantity: line.quantity + amount }]));
  return <main className="app customer-app">
    <header className="topbar customer-topbar"><button className="brand" onClick={() => window.scrollTo({ top: 0, behavior: "smooth" })} aria-label="Hasset Pastry menu"><span className="brand-mark">H</span><span><b>HASSET</b><i>pastry</i></span></button><div className="header-actions"><button className="icon-btn" onClick={() => setLanguage(language === "en" ? "am" : "en")}>{language === "en" ? "አማ" : "EN"}</button><button className="your-order" onClick={() => setOrderOpen(true)}><span>▱</span><b>Your Order</b>{count > 0 && <i>{count}</i>}</button></div></header>
    <section className="hero customer-hero"><div><p className="eyebrow">ADDIS ABABA · MADE DAILY</p><h1>A little moment<br /><span>of sweetness.</span></h1><p>{language === "en" ? "Order your favorite pastry." : "የሚወዱትን ፓስትሪ ይዘዙ።"}</p></div><div className="hero-art"><img src="https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=900&q=85" alt="Chocolate celebration cake" /><div className="stamp">BAKED<br />WITH LOVE</div></div></section>
    <section id="menu" className="menu-section"><div className="section-heading"><div><p className="eyebrow">FRESH FROM OUR KITCHEN</p><h2>{language === "en" ? "Menu" : "ምናሌ"}</h2></div></div><label className="search"><span>⌕</span><input value={query} onChange={event => setQuery(event.target.value)} placeholder={language === "en" ? "Search food..." : "ምግብ ይፈልጉ..."} /></label><nav className="categories" aria-label="Food categories">{categories.map(value => <button key={value} className={category === value ? "active" : ""} onClick={() => setCategory(value)}>{value}</button>)}</nav>{products.length ? <div className="food-grid">{products.map(food => <FoodCard key={food.id} food={food} language={language} onOpen={() => setSelected(food)} onAdd={() => add(food)} />)}</div> : <div className="empty">No pastries found. Try another search.</div>}</section>
    <section className="story"><div className="story-photo"><img src="https://images.unsplash.com/photo-1559620192-032c4bc4674e?auto=format&fit=crop&w=1000&q=85" alt="Fresh pastry making" /></div><div><p className="eyebrow">OUR LITTLE PROMISE</p><h2>Made for unhurried mornings and sweet endings.</h2><p>At Hasset, every cake and pastry is made with care, good ingredients, and a little Ethiopian warmth.</p><div className="story-points"><span>✦ Baked daily</span><span>✦ Quality ingredients</span><span>✦ Made with heart</span></div></div></section><footer className="customer-footer"><div><div className="brand"><span className="brand-mark">H</span><span><b>HASSET</b><i>pastry</i></span></div><p>Fresh cakes, pastries and coffee made with care in Addis Ababa.</p></div><div><h3>Visit us</h3><p>Addis Ababa, Ethiopia<br />Open daily · 7:00 AM – 8:00 PM</p></div><div><h3>Contact</h3><p>+251 91 000 0000<br />hello@hassetpastry.com</p></div><small>© {new Date().getFullYear()} Hasset Pastry. All rights reserved.</small></footer>
    {selected && <ProductDetail food={selected} language={language} onClose={() => setSelected(null)} onAdd={add} />}{orderOpen && <OrderPanel lines={order} total={total} onClose={() => setOrderOpen(false)} onAdjust={adjust} onClear={() => setOrder([])} />}
  </main>;
}
function FoodCard({ food, language, onOpen, onAdd }: { food: Food; language: "en" | "am"; onOpen: () => void; onAdd: () => void }) { return <article className="food-card"><button className="card-image" onClick={onOpen}><img src={food.image} alt={food.name} />{food.isSoldOut && <span className="sold">Sold out</span>}{food.featured && !food.isSoldOut && <span className="featured">Baker’s pick</span>}</button><div className="card-body"><button className="food-name" onClick={onOpen}><h3>{language === "en" ? food.name : food.nameAm}</h3><p>{language === "en" ? food.description : food.descriptionAm}</p></button><div className="card-bottom"><strong>{birr(food.price)}{food.sizes && <small>from</small>}</strong><button className="add" disabled={food.isSoldOut} onClick={onAdd} aria-label={`Add ${food.name} to your order`}>{food.isSoldOut ? "—" : "+"}</button></div></div></article>; }
function ProductDetail({ food, language, onClose, onAdd }: { food: Food; language: "en" | "am"; onClose: () => void; onAdd: (food: Food, size?: CakeSize) => void }) { const [size, setSize] = useState(food.sizes?.find(value => value.name === "1 KG") ?? food.sizes?.[0]); const [quantity, setQuantity] = useState(1); const price = size?.price ?? food.price; return <div className="overlay" role="dialog" aria-modal="true"><div className="food-modal"><button className="close" onClick={onClose}>×</button><img className="modal-image" src={food.image} alt={food.name} /><div className="modal-info"><p className="eyebrow">{food.category}</p><h2>{language === "en" ? food.name : food.nameAm}</h2><p>{language === "en" ? food.description : food.descriptionAm}</p><div className="ingredients"><b>{language === "en" ? "Ingredients" : "የተሰራባቸው"}</b><span>{(language === "en" ? food.ingredients : food.ingredientsAm).join(" · ")}</span></div>{food.sizes && <div className="sizes"><b>Choose size</b><div>{food.sizes.map(value => <button key={value.name} onClick={() => setSize(value)} className={size?.name === value.name ? "selected" : ""}>{value.name}<small>{birr(value.price)}</small></button>)}</div></div>}<div className="buy-row"><div className="stepper"><button onClick={() => setQuantity(Math.max(1, quantity - 1))}>−</button><b>{quantity}</b><button onClick={() => setQuantity(quantity + 1)}>+</button></div><button className="primary" disabled={food.isSoldOut} onClick={() => { for (let i = 0; i < quantity; i += 1) onAdd(food, size); }}>{food.isSoldOut ? "Sold out" : `Add to your order · ${birr(price * quantity)}`}</button></div></div></div></div>; }
function OrderPanel({ lines, total, onClose, onAdjust, onClear }: { lines: OrderLine[]; total: number; onClose: () => void; onAdjust: (index: number, amount: number) => void; onClear: () => void }) { return <div className="overlay order-overlay"><aside className="cart"><div className="cart-head"><div><p className="eyebrow">YOUR SELECTION</p><h2>Your order</h2></div><button className="close" onClick={onClose}>×</button></div>{lines.length ? <><div className="cart-lines">{lines.map((line, index) => <div className="cart-line" key={`${line.food.id}-${line.size?.name}`}><img src={line.food.image} alt="" /><div><b>{line.food.name}</b><small>{line.size?.name ?? line.food.category}</small><strong>{birr((line.size?.price ?? line.food.price) * line.quantity)}</strong></div><div className="mini-stepper"><button onClick={() => onAdjust(index, -1)}>−</button><span>{line.quantity}</span><button onClick={() => onAdjust(index, 1)}>+</button></div></div>)}</div><button className="clear" onClick={onClear}>Clear selection</button><div className="cart-total"><span>Total</span><b>{birr(total)}</b></div><p className="cart-reminder">Show this selection and total to your waiter when you are ready.</p><button className="primary full" onClick={onClose}>Continue browsing</button></> : <div className="empty"><span>☕</span><h3>Your order is empty</h3><p>Select something sweet to get started.</p></div>}</aside></div>; }
