"use client";

import { FormEvent, useState } from "react";
import { categories, menuItems } from "@/data/menu";
import { Category, Food } from "@/types/menu";

const birr = (price: number) => `ETB ${price.toLocaleString()}`;
const foodCategories = categories.filter((category): category is Category => category !== "All");

export default function AdminExperience() {
  const [signedIn, setSignedIn] = useState(false);
  const [items, setItems] = useState(menuItems);
  const saveFood = (food: Food) => setItems(current => current.some(item => item.id === food.id) ? current.map(item => item.id === food.id ? food : item) : [food, ...current]);
  return signedIn ? <AdminDashboard items={items} onSaveFood={saveFood} onToggle={id => setItems(current => current.map(item => item.id === id ? { ...item, isSoldOut: !item.isSoldOut } : item))} /> : <AdminLogin onLogin={() => setSignedIn(true)} />;
}

function AdminLogin({ onLogin }: { onLogin: () => void }) { return <main className="admin-route"><section className="admin-login"><div className="admin-login-art"><img src="https://images.unsplash.com/photo-1555507036-ab1f4038808a?auto=format&fit=crop&w=900&q=85" alt="Fresh Hasset pastry" /></div><form onSubmit={(event: FormEvent) => { event.preventDefault(); onLogin(); }}><div className="brand login-brand"><span className="brand-mark">H</span><span><b>HASSET</b><i>pastry</i></span></div><h1>Admin login</h1><p>Sign in to manage the Hasset Pastry menu.</p><label>Email address<input required type="email" placeholder="name@hassetpastry.com" /></label><label>Password<input required type="password" placeholder="••••••••" /></label><button className="primary full">Sign in</button></form></section></main>; }

function AdminDashboard({ items, onToggle, onSaveFood }: { items: Food[]; onToggle: (id: string) => void; onSaveFood: (food: Food) => void }) {
  const [tab, setTab] = useState("Dashboard"); const [editing, setEditing] = useState<Food | null | "new">(null);
  return <main className="admin-route"><section className="admin"><aside><div className="brand"><span className="brand-mark">H</span><span><b>HASSET</b><i>admin</i></span></div>{["Dashboard", "Menu", "Settings"].map(value => <button className={tab === value ? "nav-active" : ""} key={value} onClick={() => setTab(value)}>{value}</button>)}</aside><section className="admin-content"><div className="admin-head"><div><p className="eyebrow">HASSET PASTRY</p><h1>{tab}</h1></div></div>{tab === "Dashboard" ? <div className="stats"><article><small>Menu items</small><b>{items.filter(item => item.isVisible).length}</b><span>Currently displayed</span></article><article><small>Sold out</small><b>{items.filter(item => item.isSoldOut).length}</b><span>Needs attention</span></article><article><small>Categories</small><b>{foodCategories.length}</b><span>Across the menu</span></article></div> : tab === "Menu" ? <><div className="admin-toolbar"><input placeholder="Search menu items" /><button className="primary" onClick={() => setEditing("new")}>+ Add food</button></div><div className="table-wrap"><table><thead><tr><th>Food</th><th>Category</th><th>Price</th><th>Availability</th><th>Edit</th></tr></thead><tbody>{items.map(item => <tr key={item.id}><td><img src={item.image} alt="" /><b>{item.name}</b></td><td>{item.category}</td><td>{birr(item.price)}</td><td><button className={item.isSoldOut ? "toggle off" : "toggle on"} onClick={() => onToggle(item.id)} aria-label={`Toggle ${item.name} availability`}><i /></button><span className="availability-label">{item.isSoldOut ? "Sold out" : "Available"}</span></td><td><button className="edit-icon" onClick={() => setEditing(item)} aria-label={`Edit ${item.name}`}>✎</button></td></tr>)}</tbody></table></div></> : <Settings />}</section></section>{editing && <FoodEditor food={editing === "new" ? undefined : editing} onClose={() => setEditing(null)} onSave={food => { onSaveFood(food); setEditing(null); }} />}</main>;
}

function FoodEditor({ food, onClose, onSave }: { food?: Food; onClose: () => void; onSave: (food: Food) => void }) {
  const [preview, setPreview] = useState(food?.image ?? "https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=900&q=85");
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); const name = String(data.get("name")).trim(); const price = Number(data.get("price")); if (!name || !Number.isFinite(price)) return; onSave({ id: food?.id ?? `food-${Date.now()}`, name, nameAm: food?.nameAm ?? name, category: String(data.get("category")) as Category, description: String(data.get("description")).trim() || "Freshly made at Hasset Pastry.", descriptionAm: food?.descriptionAm ?? "በሃሴት ፓስትሪ ትኩስ የተሰራ።", ingredients: food?.ingredients ?? ["Fresh ingredients"], ingredientsAm: food?.ingredientsAm ?? ["ትኩስ ግብዓቶች"], image: String(data.get("image")).trim() || preview, price, sizes: food?.sizes, isVisible: food?.isVisible ?? true, isSoldOut: food?.isSoldOut ?? false }); };
  return <div className="overlay" role="dialog" aria-modal="true"><form className="food-editor" onSubmit={submit}><button type="button" className="close" onClick={onClose}>×</button><div className="editor-image"><img src={preview} alt="Food preview" /></div><div className="editor-body"><p className="eyebrow">MENU MANAGEMENT</p><h2>{food ? "Edit food" : "Add food"}</h2><label>Food name<input required name="name" defaultValue={food?.name} placeholder="Chocolate Cake" /></label><label>Category<select required name="category" defaultValue={food?.category ?? "Cakes"}>{foodCategories.map(category => <option key={category}>{category}</option>)}</select></label><label>Price in ETB<input required name="price" type="number" min="0" defaultValue={food?.price} placeholder="1800" /></label><label>Image URL<input required name="image" value={preview} onChange={event => setPreview(event.target.value)} /></label><label>Description<textarea name="description" defaultValue={food?.description} placeholder="Short product description" rows={3} /></label><button className="primary full">{food ? "Save food changes" : "Add food to menu"}</button></div></form></div>;
}

function Settings() { const [saved, setSaved] = useState(false); return <section className="settings"><div className="profile-row"><div className="profile-photo">HA<button aria-label="Change profile picture">✎</button></div><div><h2>Hasset Admin</h2><p>Manager · Hasset Pastry</p></div></div><form onSubmit={event => { event.preventDefault(); setSaved(true); }}><h2>Profile details</h2><div className="setting-grid"><label>Full name<input defaultValue="Hasset Admin" /></label><label>Email address<input defaultValue="admin@hassetpastry.com" type="email" /></label><label>Phone number<input defaultValue="+251 91 000 0000" /></label><label>Role<input defaultValue="Manager" /></label></div><h2>Store preferences</h2><div className="setting-grid"><label>Business name<input defaultValue="Hasset Pastry" /></label><label>Location<input defaultValue="Addis Ababa, Ethiopia" /></label></div><button className="primary">Save changes</button>{saved && <p className="save-message" role="status">✓ Your settings have been saved for this session.</p>}</form></section>; }
